function orderTaking()
// TOMA DE ORDEN

// VERIFICACION Y MODIFICACION EN INVENTARIO 


// LLAMADA A PRODUCTO PARA VERIFICAR PRECIO ACTUAL

// CALCULO DE PRECIO

// REGISTRO DE LA ORDEN

// CREACION DEL ITEM O LOS ITEMS